# utils/report_generator.py
# GaN MOSFET Report Generator with Embedded Graphs and Auto-Summary
# University of Hyderabad — Group 4

from fpdf import FPDF
import datetime, os
import plotly.io as pio

class ReportGenerator:
    def __init__(self, params, insights, figures=None, logo_path="assets/uoh_logo.png"):
        self.params = params
        self.insights = insights
        self.figures = figures or []
        self.logo_path = logo_path

    def create_pdf(self, filename="GaN_MOSFET_Report.pdf"):
        pdf = FPDF()
        pdf.add_page()

        # --- Header ---
        if os.path.exists(self.logo_path):
            pdf.image(self.logo_path, 10, 8, 25)
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "GaN MOSFET Analysis & Simulation Report", ln=1, align="C")
        pdf.set_font("Arial", "I", 11)
        pdf.cell(0, 8, "University of Hyderabad — Group 4", ln=1, align="C")
        pdf.ln(10)

        # --- Date ---
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 8, f"Generated on: {datetime.date.today()}", ln=1)
        pdf.ln(4)

        # --- Parameters ---
        pdf.set_font("Arial", "B", 13)
        pdf.cell(0, 8, "Simulation Parameters", ln=1)
        pdf.set_font("Arial", "", 11)
        for k, v in self.params.items():
            pdf.cell(0, 7, f"• {k}: {v}", ln=1)
        pdf.ln(6)

        # --- Insights / Summary ---
        pdf.set_font("Arial", "B", 13)
        pdf.cell(0, 8, "AI-Generated Summary", ln=1)
        pdf.set_font("Arial", "", 11)
        for insight in self.insights:
            pdf.multi_cell(0, 7, f"• {insight}")
        pdf.ln(6)

        # --- Insert Graphs ---
        pdf.set_font("Arial", "B", 13)
        pdf.cell(0, 8, "Simulation Graphs", ln=1)
        pdf.ln(4)

        for i, fig in enumerate(self.figures):
            temp_path = f"temp_fig_{i}.png"
            try:
                pio.write_image(fig, temp_path, width=800, height=500, scale=2)
                pdf.image(temp_path, x=15, w=180)
                pdf.ln(6)
                os.remove(temp_path)
            except Exception:
                pdf.multi_cell(0, 7, f"[Graph {i+1}] — Unable to render image offline.")
                pdf.ln(4)

        # --- Footer ---
        pdf.set_y(-35)
        pdf.set_font("Arial", "I", 9)
        pdf.multi_cell(0, 6,
            "This report was automatically generated by the GaN MOSFET Simulator Web App.\n"
            "Course: Semiconductor Materials | Faculty: Dr. Raj Kishora Dash\n"
            "© 2025 University of Hyderabad — Group 4", align="C"
        )

        pdf.output(filename)
        return filename
